---
apiVersion: v1
kind: Secret
metadata:
  name: searcher-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/assemble-dev-org/searcher-gitops